name: CentralEssentials
author: WeChanDoIt
version: 1.1
main: net.dragonessentials.src.Main
depend: [SuperBoosters]
commands:
  nv:
    usage: /nv
    description:
  help:
    usage: /help
    description:
  discord:
    usage: /discord
    description:
  centralitems:
    usage: /centralitems
    description:
  fix:
    usage: /fix
    description:
  smeltpick:
    usage: /smeltpick
    description:
  glassbreak:
    usage: /glassbreak
    description:
  annoyed:
    usage: /annoyed
    description:
  dab:
    usage: /dab
    description:
  dub:
    usage: /dub
    description:
  L:
    usage: /L
    description:
  shrug:
    usage: /shrug
    description:
  smak:
    usage: /smak
    description:
  triggered:
    usage: /triggered
    description:
  yeet:
    usage: /yeet
    description: